In [10]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# pd.reset_option('display.max_rows')

# Importing the dataset
# two_intervals = pd.read_csv('dataset_interval_two.csv')
three_intervals = pd.read_csv('dataset_interval_three.csv')
four_intervals = pd.read_csv('dataset_interval_four.csv')

## Three Visits

### MD analysis

In [22]:
from sklearn.linear_model import LinearRegression

difference_MD_3 = []
Third_y_predictions = []
Third_y_actuals = []
for i in range(0, len(three_intervals)-2, 3):
    First_X = three_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = three_intervals['md'][i]
#     print(First_Y)
    Second_X = three_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = three_intervals['md'][i+1]
#     print(Second_Y)
    Third_X = three_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = three_intervals['md'][i+2]
#     print(Third_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X]],[[First_Y], [Second_Y]])
    Third_y_pred = model.predict(Third_X)
    Third_y_actuals.append(Third_Y)
    Third_y_predictions.append(Third_y_pred)
    
#     differences = abs((Third_y_pred - Third_Y)/Third_Y)*100
    differences = abs((Third_y_pred - Third_Y))

    difference_MD_3.append([First_Y, Second_Y, Third_Y, Third_y_pred.item(0), differences.item(0)])

difference_MD_3 = pd.DataFrame(difference_MD_3)
difference_MD_3.columns = ['Visit_1_MD', 'Visit_2_MD', 'Visit_3_MD_Actual', 'Visit_3_MD_Predicted', 'Absolute difference']
difference_MD_3.describe()

,Visit_1_MD,Visit_2_MD,Visit_3_MD_Actual,Visit_3_MD_Predicted,Absolute difference
count,3238.000000,3238.000000,3238.000000,3238.000000,3238.000000
mean,0.686342,0.675392,0.663264,0.667639,0.286518
std,0.405280,0.410866,0.408685,0.669008,0.468909
min,0.000631,0.000631,0.000597,-3.417686,0.000008
25%,0.389942,0.369190,0.340604,0.224568,0.061589
50%,0.712853,0.695024,0.680769,0.630072,0.174725
75%,0.972747,0.966051,0.952796,1.011626,0.373723
max,3.176874,3.784426,2.409905,18.911508,16.883825

In [23]:
Third_y_predictions = np.array(Third_y_predictions)
Third_y_predictions = Third_y_predictions.ravel()
np.savetxt('Y_predictions_Linear_3', Third_y_predictions)
Third_y_actuals = np.array(Third_y_actuals)
Third_y_actuals
np.savetxt('Y_actuals_Linear_3', Third_y_actuals)

### VFI Analysis

In [24]:
# from sklearn.linear_model import LinearRegression

difference_VFI_3 = []
for i in range(0, len(three_intervals)-2, 3):
    First_X = three_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = three_intervals['vfi'][i]
#     print(First_Y)
    Second_X = three_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = three_intervals['vfi'][i+1]
#     print(Second_Y)
    Third_X = three_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = three_intervals['vfi'][i+2]
#     print(Third_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X]],[[First_Y], [Second_Y]])
    Third_y_pred = model.predict(Third_X)
    differences = np.array(0)
    if Third_Y != 0:
#         differences = abs((Third_y_pred - Third_Y)/Third_Y)*100
        differences = abs((Third_y_pred - Third_Y))

    difference_VFI_3.append([First_Y, Second_Y, Third_Y, Third_y_pred.item(0), differences.item(0)])

difference_VFI_3 = pd.DataFrame(difference_VFI_3)
difference_VFI_3.columns = ['Visit_1_VFI', 'Visit_2_VFI', 'Visit_3_VFI_Actual', 'Visit_3_VFI_Predicted', 'Absolute difference']
difference_VFI_3.describe()

,Visit_1_VFI,Visit_2_VFI,Visit_3_VFI_Actual,Visit_3_VFI_Predicted,Absolute difference
count,3238.000000,3238.000000,3238.000000,3238.000000,3238.000000
mean,91.063002,90.676343,90.152872,90.404146,4.840817
std,16.272103,16.633660,17.316792,19.201630,9.255617
min,1.000000,1.000000,0.000000,-115.134921,0.000000
25%,92.000000,91.000000,90.000000,89.539452,1.000000
50%,98.000000,98.000000,98.000000,97.714286,2.040436
75%,99.000000,99.000000,99.000000,100.000000,5.128036
max,100.000000,100.000000,100.000000,191.250000,191.134921

### RNFL Analysis

In [25]:
# from sklearn.linear_model import LinearRegression

difference_RNFL_3 = []
for i in range(0, len(three_intervals)-2, 3):
    First_X = three_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = three_intervals['rnfl_average'][i]
#     print(First_Y)
    Second_X = three_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = three_intervals['rnfl_average'][i+1]
#     print(Second_Y)
    Third_X = three_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = three_intervals['rnfl_average'][i+2]
#     print(Third_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X]],[[First_Y], [Second_Y]])
    Third_y_pred = model.predict(Third_X)
    
#     differences = abs((Third_y_pred - Third_Y)/Third_Y)*100
    differences = abs((Third_y_pred - Third_Y))

    difference_RNFL_3.append([First_Y, Second_Y, Third_Y, Third_y_pred.item(0), differences.item(0)])

difference_RNFL_3 = pd.DataFrame(difference_RNFL_3)
difference_RNFL_3.columns = ['Visit_1_RNFL', 'Visit_2_RNFL', 'Visit_3_RNFL_Actual', 'Visit_3_RNFL_Predicted', 'Absolute ifference']
difference_RNFL_3.describe()

,Visit_1_RNFL,Visit_2_RNFL,Visit_3_RNFL_Actual,Visit_3_RNFL_Predicted,Absolute ifference
count,3238.000000,3238.000000,3238.000000,3238.000000,3238.000000
mean,76.862878,76.494441,76.203521,76.160431,4.929004
std,13.175172,13.151847,13.086260,15.261995,6.866995
min,38.000000,38.000000,35.000000,-24.545455,0.000000
25%,68.000000,68.000000,67.000000,66.473077,1.333669
50%,77.000000,77.000000,76.000000,76.148810,3.076923
75%,86.000000,85.000000,85.000000,86.000000,6.000000
max,126.000000,133.000000,133.000000,164.000000,107.800000

### GCA Analysis

In [26]:
# from sklearn.linear_model import LinearRegression

difference_GCA_3 = []
for i in range(0, len(three_intervals)-2, 3):
    First_X = three_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = three_intervals['gca_average'][i]
#     print(First_Y)
    Second_X = three_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = three_intervals['gca_average'][i+1]
#     print(Second_Y)
    Third_X = three_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = three_intervals['gca_average'][i+2]
#     print(Third_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X]],[[First_Y], [Second_Y]])
    Third_y_pred = model.predict(Third_X)
    
#     differences = abs((Third_y_pred - Third_Y)/Third_Y)*100
    differences = abs((Third_y_pred - Third_Y))

    difference_GCA_3.append([First_Y, Second_Y, Third_Y, Third_y_pred.item(0), differences.item(0)])

difference_GCA_3 = pd.DataFrame(difference_GCA_3)
difference_GCA_3.columns = ['Visit_1_GCA', 'Visit_2_GCA', 'Visit_3_GCA_Actual', 'Visit_3_GCA_Predicted', 'Absolute difference']
difference_GCA_3.describe()

,Visit_1_GCA,Visit_2_GCA,Visit_3_GCA_Actual,Visit_3_GCA_Predicted,Absolute difference
count,3238.000000,3238.000000,3238.000000,3238.000000,3238.000000
mean,70.523780,70.204447,69.898394,69.968684,2.677093
std,9.680239,9.658370,9.696564,16.656212,13.569391
min,24.000000,28.000000,28.000000,-231.657143,0.000000
25%,65.000000,65.000000,64.000000,64.000000,0.733800
50%,71.000000,71.000000,70.500000,70.739963,1.212038
75%,77.000000,77.000000,77.000000,77.000000,2.459989
max,99.000000,99.000000,103.000000,729.000000,656.000000

## Four Visits

### MD Analysis

In [27]:
# from sklearn.linear_model import LinearRegression

difference_MD_4 = []
Fourth_y_predictions = []
Fourth_y_actuals = []
for i in range(0, len(four_intervals)-3, 4):
    First_X = four_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = four_intervals['md'][i]
#     print(First_Y)
    Second_X = four_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = four_intervals['md'][i+1]
#     print(Second_Y)
    Third_X = four_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = four_intervals['md'][i+2]
#     print(Third_Y)
    Fourth_X = four_intervals['days_from_baseline'][i+3]
#     print(Fourth_X)
    Fourth_Y = four_intervals['md'][i+3]
#     print(Fourth_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X], [Third_X]],[[First_Y], [Second_Y], [Third_Y]])
    Fourth_y_pred = model.predict(Fourth_X)
    Fourth_y_actuals.append(Fourth_Y)
    Fourth_y_predictions.append(Fourth_y_pred)
    
#     differences = abs((Fourth_y_pred - Fourth_Y)/Fourth_Y)*100
    differences = abs((Fourth_y_pred - Fourth_Y))
    difference_MD_4.append([First_Y, Second_Y, Third_Y, Fourth_Y, Fourth_y_pred.item(0), differences.item(0)])

difference_MD_4 = pd.DataFrame(difference_MD_4)
difference_MD_4.columns = ['Visit_1_MD', 'Visit_2_MD', 'Visit_3_MD', 'Visit_4_MD_Actual', 'Visit_4_MD_Predicted', 'Absolute difference']
difference_MD_4.describe()

,Visit_1_MD,Visit_2_MD,Visit_3_MD,Visit_4_MD_Actual,Visit_4_MD_Predicted,Absolute difference
count,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000,2.421000e+03
mean,0.696890,0.685792,0.674736,0.663202,0.659336,1.974602e-01
std,0.402185,0.408729,0.407119,0.413322,0.465509,2.260186e-01
min,0.000664,0.000631,0.000631,0.000597,-1.306861,3.803599e-07
25%,0.406443,0.381944,0.364754,0.335738,0.268962,4.695198e-02
50%,0.731139,0.709578,0.695024,0.679204,0.653871,1.351653e-01
75%,0.986279,0.979490,0.968278,0.952796,0.975248,2.691077e-01
max,2.177710,3.176874,2.409905,2.409905,3.007492,2.660296e+00

In [28]:
Fourth_y_predictions = np.array(Fourth_y_predictions)
Fourth_y_predictions = Fourth_y_predictions.ravel()
np.savetxt('Y_predictions_Linear_4', Fourth_y_predictions)

In [29]:
Fourth_y_actuals = np.array(Fourth_y_actuals)
Fourth_y_actuals
np.savetxt('Y_actuals_Linear_4', Fourth_y_actuals)

### VFI Analysis

In [30]:
# from sklearn.linear_model import LinearRegression

difference_VFI_4 = []
for i in range(0, len(four_intervals)-3, 4):
    First_X = four_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = four_intervals['vfi'][i]
#     print(First_Y)
    Second_X = four_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = four_intervals['vfi'][i+1]
#     print(Second_Y)
    Third_X = four_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = four_intervals['vfi'][i+2]
#     print(Third_Y)
    Fourth_X = four_intervals['days_from_baseline'][i+3]
#     print(Fourth_X)
    Fourth_Y = four_intervals['vfi'][i+3]
#     print(Fourth_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X], [Third_X]],[[First_Y], [Second_Y], [Third_Y]])
    Fourth_y_pred = model.predict(Fourth_X)
    
    differences = np.array(0)
    if Fourth_Y != 0:
#         differences = abs((Fourth_y_pred - Fourth_Y)/Fourth_Y)*100
        differences = abs((Fourth_y_pred - Fourth_Y))
    difference_VFI_4.append([First_Y, Second_Y, Third_Y, Fourth_Y, Fourth_y_pred.item(0), differences.item(0)])

difference_VFI_4 = pd.DataFrame(difference_VFI_4)
difference_VFI_4.columns = ['Visit_1_VFI', 'Visit_2_VFI', 'Visit_3_VFI', 'Visit_4_VFI_Actual', 'Visit_4_VFI_Predicted', 'Absolute difference']
difference_VFI_4.describe()

,Visit_1_VFI,Visit_2_VFI,Visit_3_VFI,Visit_4_VFI_Actual,Visit_4_VFI_Predicted,Absolute difference
count,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000
mean,91.477076,91.050805,90.673689,90.086741,90.169590,3.327127
std,15.542211,16.005432,16.291916,17.199435,17.491947,5.538873
min,4.000000,1.000000,1.000000,0.000000,-10.753044,0.000000
25%,92.000000,91.000000,90.000000,90.000000,89.370722,0.630491
50%,98.000000,98.000000,98.000000,98.000000,97.512502,1.617566
75%,99.000000,99.000000,99.000000,99.000000,99.450539,3.714658
max,100.000000,100.000000,100.000000,100.000000,142.526054,100.606793

### RNFL Analysis

In [31]:
# from sklearn.linear_model import LinearRegression

difference_RNFL_4 = []
for i in range(0, len(four_intervals)-3, 4):
    First_X = four_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = four_intervals['rnfl_average'][i]
#     print(First_Y)
    Second_X = four_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = four_intervals['rnfl_average'][i+1]
#     print(Second_Y)
    Third_X = four_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = four_intervals['rnfl_average'][i+2]
#     print(Third_Y)
    Fourth_X = four_intervals['days_from_baseline'][i+3]
#     print(Fourth_X)
    Fourth_Y = four_intervals['rnfl_average'][i+3]
#     print(Fourth_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X], [Third_X]],[[First_Y], [Second_Y], [Third_Y]])
    Fourth_y_pred = model.predict(Fourth_X)
    
    differences = np.array(0)
#     if Fourth_Y != 0:
#     differences = abs((Fourth_y_pred - Fourth_Y)/Fourth_Y)*100
    differences = abs((Fourth_y_pred - Fourth_Y))
    difference_RNFL_4.append([First_Y, Second_Y, Third_Y, Fourth_Y, Fourth_y_pred.item(0), differences.item(0)])

difference_RNFL_4 = pd.DataFrame(difference_RNFL_4)
difference_RNFL_4.columns = ['Visit_1_RNFL', 'Visit_2_RNFL', 'Visit_3_RNFL', 'Visit_4_RNFL_Actual', 'Visit_4_RNFL_Predicted', 'Absolute difference']
difference_RNFL_4.describe()

,Visit_1_RNFL,Visit_2_RNFL,Visit_3_RNFL,Visit_4_RNFL_Actual,Visit_4_RNFL_Predicted,Absolute difference
count,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000
mean,76.817431,76.437423,76.180504,75.868236,75.811219,3.397121
std,12.985836,12.966992,12.889904,12.817940,13.521365,4.089355
min,38.000000,38.000000,40.000000,40.000000,29.477834,0.000000
25%,68.000000,68.000000,68.000000,67.000000,66.712649,1.000000
50%,77.000000,77.000000,76.000000,76.000000,75.885355,2.298033
75%,86.000000,85.000000,85.000000,85.000000,84.747338,4.318152
max,124.000000,123.000000,133.000000,131.000000,133.327483,44.522166

### GCA Analysis

In [32]:
# from sklearn.linear_model import LinearRegression

difference_GCA_4 = []
for i in range(0, len(four_intervals)-3, 4):
    First_X = four_intervals['days_from_baseline'][i]
#     print(First_X)
    First_Y = four_intervals['gca_average'][i]
#     print(First_Y)
    Second_X = four_intervals['days_from_baseline'][i+1]
#     print(Second_X)
    Second_Y = four_intervals['gca_average'][i+1]
#     print(Second_Y)
    Third_X = four_intervals['days_from_baseline'][i+2]
#     print(Third_X)
    Third_Y = four_intervals['gca_average'][i+2]
#     print(Third_Y)
    Fourth_X = four_intervals['days_from_baseline'][i+3]
#     print(Fourth_X)
    Fourth_Y = four_intervals['gca_average'][i+3]
#     print(Fourth_Y)
    
    
    model = LinearRegression()
    model.fit([[First_X], [Second_X], [Third_X]],[[First_Y], [Second_Y], [Third_Y]])
    Fourth_y_pred = model.predict(Fourth_X)
    
    differences = np.array(0)
#     if Fourth_Y != 0:
#     differences = abs((Fourth_y_pred - Fourth_Y)/Fourth_Y)*100
# this is now the mean abs error only
    differences = abs((Fourth_y_pred - Fourth_Y))

    difference_GCA_4.append([First_Y, Second_Y, Third_Y, Fourth_Y, Fourth_y_pred.item(0), differences.item(0)])

difference_GCA_4 = pd.DataFrame(difference_GCA_4)
difference_GCA_4.columns = ['Visit_1_GCA', 'Visit_2_GCA', 'Visit_3_GCA', 'Visit_4_GCA_Actual', 'Visit_4_GCA_Predicted', 'Absolute difference']
difference_GCA_4.describe()

,Visit_1_GCA,Visit_2_GCA,Visit_3_GCA,Visit_4_GCA_Actual,Visit_4_GCA_Predicted,Absolute difference
count,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000,2421.000000
mean,70.653862,70.359356,70.041718,69.757125,69.613988,1.786629
std,9.581662,9.516001,9.551617,9.517430,10.721381,5.128229
min,28.000000,32.000000,30.000000,28.000000,-106.557377,0.000000
25%,65.000000,65.000000,64.000000,64.000000,64.000000,0.448943
50%,71.000000,71.000000,71.000000,70.000000,70.294344,1.000000
75%,77.000000,77.000000,77.000000,76.000000,76.738157,1.823395
max,99.000000,99.000000,99.000000,103.000000,117.439369,186.557377